### ISSUE TITLE
 E_WARNING stream_socket_sendto(): Permission denied

### ISSUE THREAD

**Issue by utolich** [walkor/Workerman#649] opened 2021-07-27 13:51 UTC
Hello

```
--------------------------------------- WORKERMAN ----------------------------------------
Workerman version:4.0.19          PHP version:7.3.19
---------------------------------------- WORKERS -----------------------------------------
proto   user            worker          listen              processes    status
tcp     root            none            udp://0.0.0.0:67    1             [OK]
------------------------------------------------------------------------------------------
```

```
$udp = new \Workerman\Connection\AsyncUdpConnection('udp://192.168.33.255:' . $connection->getRemotePort());
$udp->send($response);
$udp->close();
```

catching:

E_WARNING stream_socket_sendto(): Permission denied
 in /usr/local/socket/vendor/workerman/workerman/Connection/AsyncUdpConnection.php 130

**Comment by walkor** [comment] 2021-09-09 13:19
It seems to be a permission problem. It may be caused by system configuration, such as firewall or big udp package size or other something I dn’t know. AnsyncUdpConnection is not documented and it should not be used. Please use stream_socket_client and  stream_socket_sendto to send udp data. I can't provide more help so close the issue.

**Closed by walkor** 2021-09-09 13:19 UTC
